### ISSUE TITLE
Usage along with testing-library (jest-dom, react)

### ISSUE THREAD

**Issue by jgoux** [playwright-community/jest-playwright#109]
Hello,

I'd like to give jest-playwright a try to make e2e tests inside my project.

Right now I'm using [testing-library](https://testing-library.com/docs/react-testing-library/intro) to unit/integration test my React components.

I tried adding jest-playwright to my project to add e2e tests but now my test suite is failing with this error for every tests (even non e2e tests) : 

```
FAIL  src/components/App/Login.test.tsx
  ● Test suite failed to run

    Protocol error (Target.setAutoAttach): Target closed.

      at node_modules/playwright-core/lib/chromium/crConnection.js:123:63
      at CRSession.send (node_modules/playwright-core/lib/chromium/crConnection.js:122:16)
      at CRSession.<anonymous> (node_modules/playwright-core/lib/helper.js:87:31)
      at Function.connect (node_modules/playwright-core/lib/chromium/crBrowser.js:59:27)
      at Chromium.launch (node_modules/playwright-core/lib/server/chromium.js:44:53)
      at getBrowserPerProcess (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:58:33)
      at PlaywrightEnvironment.setup (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:107:31)
        -- ASYNC --
      at CRSession.<anonymous> (node_modules/playwright-core/lib/helper.js:66:23)
      at Function.connect (node_modules/playwright-core/lib/chromium/crBrowser.js:59:27)
      at Chromium.launch (node_modules/playwright-core/lib/server/chromium.js:44:53)
      at getBrowserPerProcess (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:58:33)
      at PlaywrightEnvironment.setup (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:107:31)
```

I looked for this error and it seems that it's related to `browser.close()` : https://github.com/puppeteer/puppeteer/issues/1947#issuecomment-401920176

But I have no idea how to fix it.

Also, I'm surprised that this error also happens in my integration tests where I don't use playwright at all. Is there any way to run playwright only for a subset of my tests files? In my case all my e2e files have a specific `e2e.ts` extension.

Here is my repo : https://github.com/jgoux/storyflow
Doing a `yarn install && yarn test` should repro the error.

Thanks for your help.

**EDIT** : I was able to fix the separation of the configuration of jest using https://jestjs.io/docs/en/configuration.html#projects-arraystring--projectconfig 🌟 

But the error remains on the e2e test I added.

**Comment by mxschmitt** [comment]
Hello,
which operating system are you using?

this message mostly comes along if you haven't installed all the required dependencies of the browsers.

**Comment by jgoux** [comment]
I'm using WSL2 (Ubuntu).
I installed all the required system dependencies from https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic

Maybe WSL2 needs special arguments to launch Chromium.
