### ISSUE TITLE
Unable to use @next version of playwright

### ISSUE THREAD

**Issue by celeryclub** [playwright-community/jest-playwright#125]
Hey team. 0.2.0 is looking good! Thanks for all your work on that.

I'm trying to test a bugfix in playwright that hasn't been released yet. I'm running `npm i --save playwright-chromium@next` to get the latest commit, but when I do that I get the following error.

<details>
<summary>Error: Cannot find module 'playwright-core'.</summary>
Error: Cannot find module 'playwright-core'
Require stack:
- /Users/steve/adobe/behance/be.net/test/e2e/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js
- /Users/steve/adobe/behance/be.net/test/e2e/node_modules/jest-playwright-preset/runner.js
- /Users/steve/adobe/behance/be.net/test/e2e/node_modules/@jest/core/build/TestScheduler.js
- /Users/steve/adobe/behance/be.net/test/e2e/node_modules/@jest/core/build/jest.js
- /Users/steve/adobe/behance/be.net/test/e2e/node_modules/jest/node_modules/jest-cli/build/cli/index.js
- /Users/steve/adobe/behance/be.net/test/e2e/node_modules/jest/node_modules/jest-cli/bin/jest.js
- /Users/steve/adobe/behance/be.net/test/e2e/node_modules/jest/bin/jest.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/steve/adobe/behance/be.net/test/e2e/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:8:43)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
</details>

I'm guessing this has something to do with the dynamic require. Is there an easy fix to this issue?

Thanks for looking!

**Comment by mxschmitt** [comment]
Hey!

Probably its because the require of playwright-core there to get the devices: https://github.com/playwright-community/jest-playwright/blob/76c7fa2adab652f5e58d2d39dbf9cf7b6729aded/src/PlaywrightRunner.ts#L57-L62

Can we do it with getPlaywrightInstance? @mmarkelov

**Comment by mmarkelov** [comment]
@mxschmitt youp! I suppose we can. I should take a look

**Comment by mmarkelov** [comment]
Should be fixed in #127 
I'll publish new version with this fix soon
