### ISSUE TITLE
[Question] Websocket error when running tests in docker

### ISSUE THREAD

**Issue by Goolyio** [playwright-community/jest-playwright#310]
I am struggling to run my jest tests within a docker container running the [playwright image](https://hub.docker.com/_/microsoft-playwright) as I get this error.
```
> jest

FAIL browser: chromium tests/index.test.js
  ● Test suite failed to run

    browserType.connect: WebSocket error: Unexpected server response: 426
    =========================== logs ===========================
    [browser] <ws connecting> ws://127.0.0.1:36355/177bef362d19a5269917627bf3143262
    [browser] <ws connect error> ws://127.0.0.1:36355/177bef362d19a5269917627bf3143262 Unexpected server response: 426
    [browser] <ws disconnected> ws://127.0.0.1:36355/177bef362d19a5269917627bf3143262
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

      at WebSocket.<anonymous> (node_modules/playwright-chromium/lib/transport.js:119:24)
      at WebSocket.onError (node_modules/playwright-chromium/node_modules/ws/lib/event-target.js:128:16)
      at abortHandshake (node_modules/playwright-chromium/node_modules/ws/lib/websocket.js:718:15)
      at ClientRequest.<anonymous> (node_modules/playwright-chromium/node_modules/ws/lib/websocket.js:595:7)

then
undefined
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.424 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! remo-basic-tester@1.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the remo-basic-tester@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pwuser/.npm/_logs/2020-08-25T16_08_11_004Z-debug.log
```
I am using the jest preset environment and playwright-chromium and it works great when not in a container. Here is my launch options object which I got from another issue but didn't work:

```js
{
    headless: false,
    devtools: false,
    args: [
      "--disable-gpu",
      "--renderer",
      "--no-sandbox",
      "--no-service-autorun",
      "--no-experiments",
      "--no-default-browser-check",
      "--disable-dev-shm-usage",
      "--disable-setuid-sandbox",
      "--no-first-run",
      "--no-zygote",
      "--single-process",
      "--disable-extensions",
    ], //These are only for docker
    chromiumSandbox: false,
  }
```
I couldn't find anything on google relating to this so any help would be appreciated. Please let me know if you need more details, thanks in advance 😄

**Comment by Goolyio** [comment]
Turns out I'm a idiot and didn't expose ports 80 and 443 in the docker container 😢.
