### ISSUE TITLE
Video is not recording anymore after updating to 1.12.0

### ISSUE THREAD

**Issue by kemsky** [playwright-community/jest-playwright#749]
**Describe the bug**
This is the follow up to #708

The same repo https://github.com/kemsky/playwright-video-bug,  but playwright version is updated to 1.12.0.

Error:
```
  ● Test suite failed to run

    .saveAs: Browser has been closed

      13 |
      14 |     async teardown() {
    > 15 |         await Promise.all([
         |         ^
      16 |             this.global.page.video().saveAs(`playwright\\videos\\${this.global.expect.getState().currentTestName.replace(/[\s/\\?%*:|"<>]/g, '_')}.webm`),
      17 |             super.teardown()
      18 |         ]);

      at Object.captureStackTrace (../node_modules/playwright-chromium/lib/utils/stackTrace.js:51:19)
      at Connection.sendMessageToServer (../node_modules/playwright-chromium/lib/client/connection.js:69:48)
      at Proxy.<anonymous> (../node_modules/playwright-chromium/lib/client/channelOwner.js:64:61)
      at ../node_modules/playwright-chromium/lib/client/artifact.js:64:42
      at Artifact._wrapApiCall (../node_modules/playwright-chromium/lib/client/channelOwner.js:77:34)
      at Artifact.saveAs (../node_modules/playwright-chromium/lib/client/artifact.js:59:21)
      at Video.saveAs (../node_modules/playwright-chromium/lib/client/video.js:47:25)
          at async Promise.all (index 0)
      at JestPlaywrightEnvironment.teardown (../jest.playwright.environment.js:15:9)

```

**To Reproduce**
https://github.com/kemsky/playwright-video-bug

**Desktop (please complete the following information):**
<pre>
## System:
 - OS: Windows 10 10.0.19042
 - Memory: 6.74 GB / 31.75 GB
## Binaries:
 - Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - playwright: 1.12.0 => 1.12.0
 - playwright-core: 1.12.0 => 1.12.0

</pre>

**Comment by mxschmitt** [comment]
Was this working with 1.11 and is broken since 1.12?

**Comment by kemsky** [comment]
@mxschmitt, yes, a simple upgrade breaks this code.

**Comment by mxschmitt** [comment]
This seems to work:

```js
        await Promise.all([
            this.global.page.video().saveAs(`playwright/videos/${this.global.expect.getState().currentTestName.replace(/[\s/\\?%*:|"<>]/g, '_')}.webm`),
            this.global.context.close()
        ]);
        await super.teardown()
```

**Comment by mxschmitt** [comment]
Closing since it seems stale as part of the triage process.
