### ISSUE TITLE
Support Jest 28

### ISSUE THREAD

**Issue by davidglezz** [playwright-community/jest-playwright#796]
**Describe the bug**
After upgrade to Jest 28 I get:

```
TypeError: Cannot read properties of undefined (reading 'serial')
    at PlaywrightRunner.runTests (/.../node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:127:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TestScheduler.scheduleTests (/.../node_modules/@jest/core/build/TestScheduler.js:317:13)
    at async runJest (/.../node_modules/@jest/core/build/runJest.js:407:19)
    at async _run10000 (/.../node_modules/@jest/core/build/cli/index.js:338:7)
    at async runCLI (/.../node_modules/@jest/core/build/cli/index.js:190:3)
    at async Object.run (/.../node_modules/jest-cli/build/cli/index.js:155:37)
```

**To Reproduce**
- Use Jest 28 with this preset.

**Expected behavior**
That jest-playwright support Jest 28 and that it does not fail.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: macOS
 - Playwright version 1.21.0
 - jest-playwright version 1.7.0
 - jest 28

**Jest configuration (Either in the package.json > jest or in the `jest.config.js`):**

 ```js
<enter your Jest config here>
```

**Additional context**

**Comment by itayadler** [comment]
this issue still occurs with latest version v3.0.1 and latest jest v29.4.2, to fix it I went all the way back to playwright-community/jest-playwright#d7dd2fc7c348474d065526e696b922139fe5971c 
as it doesn't have this commit [the chore: bump dependencies commit which causes the issue I think.](https://github.com/playwright-community/jest-playwright/commit/27d71bd4a9d66d90013e99cab94c246e8f6d59ac)
which I think causes the issue, WDYT?
